port = "8181"
bot_address = "http://localhost:9001/bot/play"

[player]
    [player.state]
        burning = [
            "https://www.myinstants.com/media/sounds/pegando-fogo-bicho.mp3",
            "https://www.myinstants.com/media/sounds/pegando-fogo-bicho2.mp3",
            "https://www.myinstants.com/media/sounds/pegando-fogo-bicho3.mp3",
        ]
        flashed = [
            "https://www.myinstants.com/media/sounds/derruba.mp3",
            "https://www.myinstants.com/media/sounds/derruba2.mp3",
            "https://www.myinstants.com/media/sounds/derruba3.mp3",
        ]